# Generated by Django 5.1.7 on 2025-03-12 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(choices=[('N', 'Sin estudios'), ('B', 'Bachillerato'), ('L', 'Licenciatura'), ('P', 'Posgrado')], default='Sin estudios', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Mikel', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Barajas', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='field_of_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fieldofstudy'),
        ),
    ]
