# Generated by Django 5.1.7 on 2025-03-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fieldofstudy_user_education_level_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.CharField(choices=[('N', 'Sin estudios'), ('B', 'Bachillerato'), ('L', 'Licenciatura'), ('P', 'Posgrado')], default='N', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
