# Generated by Django 5.1.7 on 2025-03-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_document_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
