# Generated by Django 5.1.7 on 2025-03-19 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_document_created_at_alter_document_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authordocument',
            old_name='user',
            new_name='author',
        ),
    ]
