# Generated by Django 5.1.7 on 2025-03-19 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_user_authordocument_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveddocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='saveddocument',
            name='user',
        ),
        migrations.DeleteModel(
            name='AuthorDocument',
        ),
        migrations.DeleteModel(
            name='SavedDocument',
        ),
    ]
