# Generated by Django 5.1.7 on 2025-04-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_chatsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='id',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
