# Generated by Django 5.1.7 on 2025-04-17 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_authoreddocument_saveddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoreddocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
