# Generated by Django 5.1.8 on 2025-05-07 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='satisfactionsurveyresponse',
            old_name='response_data',
            new_name='survey',
        ),
    ]
