# Generated by Django 5.1.8 on 2025-05-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_login',
        ),
    ]
