# Generated by Django 5.1.9 on 2025-05-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_user_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='repository_id',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
