---
name: Checks

on: [push, pull_request]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-24.04
    env:
      USE_RAGFLOW: false
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && coverage run --data-file=/tmp/.coverage --source='.' manage.py test && cp /tmp/.coverage /app/.coverage"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
      - name: Coverage
        run: docker compose run --rm app sh -c "coverage run --data-file=/tmp/.coverage --source='.' manage.py test && ls /tmp"
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ github.token }}
